---
title: "Data Cleaning"
author: "Abdus Samad"
date: "2022-09-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r pacakages, warning=FALSE, include = FALSE}
library(tidyverse)
library(lubridate)

```

```{r}

 dataRaw <- read_csv("Data/Data - DS C1 Course.csv")
 head(dataRaw, n = 10)
```
```{r variables rename}

dataRenamed <- dataRaw %>% rename("Id"= "Student ID", "Date_time" = "Timestamp", "Qr_Uni_Col" = "Name of University or College currently or previously attended?")

# check for renaming
names(dataRenamed[1:10])
```

```{r variables selection}
dataselected <- select(dataRenamed, Id, Date_time, Qr_Uni_Col, Payment)

# MAKING id AS row name

dataselected <- column_to_rownames(dataselected, var= "Id")

head(dataselected)

```

```{r}
# Converting time column to date time format

# Separating date and time into different column
dataselected <- tidyr::separate(dataselected, Date_time, c("Date", "Time"), sep = " ")


head(dataselected)
```

```{r grouped the data}
# now we grouped the data by day to check how many registeration done per on each day

groupeddata <- dataselected %>% 
  group_by(Payment) %>% 
  summarize(grouped = n())

```
```{r creating ggplot}

ggplot(data = groupeddata, aes(x= Payment)) +
  geom_bar(color = "red") +
  xlab("Payment Status")
  
```
# What is distribution of University

```{r}
dataselected %>% 
  select(Qr_Uni_Col) %>% 
  distinct() %>% 
  count()

```
```{r}
head(unique(x= dataselected$Qr_Uni_Col ))


```
we are cleaning the Qr_Uni_Col column to remvoe duplicates and make its consisitent

```{r}
datacategorized <- dataselected %>% 
  mutate( 
    Uni_col = case_when(
    str_detect(
      Qr_Uni_Col,
      "Iba|Institue of Business Administration|IBA Karachi|iba karachi|BUSINESS ADMINISTRATION|INSTITUTE|") ~ "IBA",
    str_detect(
      Qr_Uni_Col,
      "AZAM|Quaid I Azam University|Quiad e Azam University|Quiad-e-Azam University islamabad|Quiad e Azam University Islamabad|Quiad-I-Azam University|Quiad-i-Azam University Islamabad|Quaid i Azam university") ~ "QU",
    str_detect(
      Qr_Uni_Col,
      "Sir Syed Univeristy of Engineering Technology|Sir syed univeristy of engineering & technology|Sir Syed Univeristy of engineering And technology|Sir Syed univeristy of engineering and technology|Sirsyed Univeristy of Engineering Technology|Sir syed Univeristy Of Engineering Technology|Sir Syed univeristy of engineering technology|Sir Syed Univeristy Engineering Technology") ~ "SYED",
    str_detect(
      Qr_Uni_Col,
      "NED university|NED University of Engineering and Technology Karachi|NED|ned University")~"NED",
    str_detect(Qr_Uni_Col, "iqra|IQRA|Iqra|iqra university") ~ "IQRA",
    str_detect(Qr_Uni_Col, "Sindh") ~ "SMIU",
    str_detect(Qr_Uni_Col, "Karachi|Univeristy of karachi") ~ "KU",
    str_detect(Qr_Uni_Col, "Szabist") ~ "SZABIST",
    str_detect(Qr_Uni_Col, "Management|management") ~ "IOBA",
    str_detect(Qr_Uni_Col, "Univeristy of engineering and technology Peshawar") ~ "UET",
    TRUE ~ Qr_Uni_Col
   )
 )

```



