---
title: "DS Course Data"
author: "Abdus Samad"
date: "2022-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read Dataset

```{r}

library(tidyverse)
library(ggplot2)

```
## Importing the Data

```{r, warning=FALSE , message=FALSE}
course_data <- read_csv("Data/Data - DS C1 Course.csv")


```
## Exploratory Data Analysis (EDA)

```{r EDA, echo=FALSE}


```

## Running Python in R

We will demonstrate how to run Python within R.


```{r}
library(reticulate)
```


```{python}
# import pandas as pd
# import numpy as np

```



```{python}

for i in range(10):
   print(i)
   
```
## Data Summary


```{r , echo=FALSE}

summary(course_data)
 
```

## Attribute name of the Dataset

```{r , echo= FALSE}
colnames(course_data)

```

now we will check the null vlaues in our dataset

```{r}
is.na(course_data)

```
```{r}

ggplot(course_data, aes(x = Age, y = `Which City are you currently residing in?`))+
  geom_point()

```


```{r}

 print("first R lesson")

```
```{r}
print(23)

```
```{r}
x <- "first R lesson"
x
```

```{r}

z <- "first"

cat(z, "R lesson")
sprintf("%s R lesson.", z)

```

```{r}
y <- "Cube"
cat(y, "Statistica Cohort 1.")
sprintf("%s Statistica Cohort 1.",y)

```
```{r}

course_data %>% select(Age) %>% n_distinct()

```
```{r}
ggplot(course_data, aes(x=Age, y = Gender) )+
  geom_bar(stat = "identity")

```
```{r}
course_data %>% group_by(`Do you understand that this is a paid course ?...21`) %>% count()

```

```{r}
ggplot(course_data, aes(x = `Do you understand that this is a paid course ?...21`, y= Gender))+
  geom_bar(stat = "identity")

```

