---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(kableExtra)
```

# Data Analysis

Column
-----------------------------------------------------------------------

### Count if it  is a paid course

```{r}
dfRaw <- read_csv("Data/Data - DS C1 Course.csv")

```

```{r}

 df_paid <- dfRaw %>% group_by(`Do you understand that this is a paid course ?...21`) %>%  count()

ggplot(df_paid, aes(x = `Do you understand that this is a paid course ?...21`, y = n))+ geom_bar(stat = "identity", fill = "yellow")

```
### Count of Age

```{r}

df_age <- dfRaw %>% group_by(Age) %>%  count()

ggplot(df_age, aes(x = Age, y = n)) + geom_bar(stat = "identity", fill = "blue")

```

# Summary of Data 

Column
-----------------------------------------------------------------------

### Chart B

```{r}

head(dfRaw)

```

### Chart C

```{r}

```

### Abdus's Flexdashboard

Column
-----------------------------------------------------------------------


```{r}

dfRaw %>% colnames()

```
# Statistics



```{r}
dfRaw %>% group_by(Gender, Payment) %>% count() %>% kable()

```

# Tidy Pacakges Functions

### Filter()

```{r}

# filteirng the data of only male

filter(dfRaw, Gender == "Male")

```
```{r}
male <- filter(dfRaw, Gender == "Male")

```

### Arrange()

```{r}

# Arrange the data by Age & Gender
arrangeByAgeGender <- arrange(dfRaw, Age, Gender)
head(arrangeByAgeGender)
tail(arrangeByAgeGender)

```

### Select()

```{r}
selectedVars <- select(dfRaw, Gender, Age) %>% kable()
selectedVars

```
### Mutate()

```{r}

mutateAppend <- mutate(dfRaw, binary = if_else(Gender == "Male", true = 1, false = 0))


```
### Grouby() & Summarize()

```{r}
dfRaw$Age <- as.numeric(dfRaw$Age)
group_by(dfRaw, Age) %>% summarize( gender_count = n(), Age_mean = mean(x = Age))

```

