---
title: "Muzammil_DS_Course"
author: "Syed Muzammil Iqbal"
date: "2022-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Read Dataset

```{r}

require(tidyverse)
require(ggplot2)
```
```{r}

course_data <- read_csv("Data/Data - DS C1 Course.csv")

```

## Data Summary

```{r}
summary(course_data)


```
## Data Column Names

```{r, echo=FALSE}
colnames(course_data)



```
```{r}
is.na(course_data)


```
```{r}

ggplot(course_data, aes(Age, "Which Country are you currently residing in?"))+
  geom_point()

```
```{r}
ggplot(course_data, aes(Age, "Which Country are you currently residing in?"))+
  geom_bar(stat="identity")

```

```{r}
course_data %>% select(Age) %>% n_distinct()


```


```{r}
course_data %>% group_by(`Do you understand that this is a paid course ?...3`) %>% count()


```

```{r}
ggplot(course_data, aes(`Do you understand that this is a paid course ?...3`, Gender)) +
  geom_bar(stat = "identity")


```





















